name: Run Worker Script

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 15 minutes (adjust as needed)
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  run-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run worker
        env:
          API_URL: ${{ secrets.API_URL }}
        run: node worker.js

